### ISSUE TITLE
C-Task-012: Messages internationalised

### ISSUE THREAD

**Issue by antferdom** [antferdom/Acme-Planner#12]
The **messages** that the system shows must be available in both **English** and **Spanish**. Data like **moments** and **money** amounts must be **internationalised** when they are **entered** or **shown**. **Textual data** like titles or descriptions are **not** expected to be **internationalised**.

**Comment by rodgarcas** [comment]
17745cbce59eddff8d84d88d0d8d4ec1c51df8ba added spanish & english messages
