### ISSUE TITLE
Testing-Comment

### ISSUE THREAD

**Issue by rodgarcas** [antferdom/Acme-Planner#74]
Every test case must include a **HEADER COMMENT** in which you make it clear the **feature** that is going to be tested (**including the constraints that are violated**) and the **expected results**.

**Comment by antferdom** [comment]
# Testing header comment template

**Feature**: `feature name` & optional `relative path`
**Imposed restrictions**: `listing the associated restrictions names associated to the task to be performed`
**Violated restrictions**: `listing the names of the violated restrictions`
**Expected result**: `textual description of the expected outcome`
